---
name: Workflow linter

on:
  pull_request:
    paths:
      - .github/workflows/**

permissions: read-all

jobs:
  call-workflow:
    uses: bitwarden/gh-actions/.github/workflows/workflow-linter.yml@f1125802b1ccae8c601d7c4f61ce39ea254b10c8
    permissions:
      contents: read
      checks: write
      pull-requests: write
